import { test } from 'node:test';
import assert from 'node:assert/strict';
import { pickPassage, buildGroundedSystemPrompt, groundedReply } from '../src/grounded-reply.js';
import { createGlooClient } from '../src/gloo-client.js';
import { findByReference } from '../src/fixtures.js';

test('pickPassage matches an anxiety-related question to Philippians 4:6-7', () => {
  const { reference, matchedKeyword } = pickPassage('I am so anxious about my exam tomorrow, what should I do?');
  assert.equal(reference, 'Philippians 4:6-7');
  assert.equal(matchedKeyword, 'anxious');
});

test('pickPassage falls back to the default passage with no matched keyword for an unrelated topic', () => {
  const { reference, matchedKeyword } = pickPassage('what is the capital of France');
  assert.equal(reference, 'Psalm 23:1-6');
  assert.equal(matchedKeyword, null);
});

test('buildGroundedSystemPrompt embeds the canonical text verbatim and requires verbatim quoting', () => {
  const passage = findByReference('Philippians 4:13');
  const prompt = buildGroundedSystemPrompt(passage);
  assert.match(prompt, /Philippians 4:13/);
  assert.ok(prompt.includes(passage.text));
  assert.match(prompt, /verbatim/);
});

test('buildGroundedSystemPrompt includes the declared interpretive-posture block and its precedence order', () => {
  const passage = findByReference('Philippians 4:13');
  const prompt = buildGroundedSystemPrompt(passage);
  assert.match(prompt, /Interpretive posture \(declared, not hidden\)/);
  assert.match(prompt, /Romans 6:14/);
  assert.match(prompt, /1 John 4:18/);
  assert.match(prompt, /John 14:9/);
  assert.match(prompt, /never make a passage say more than its own words say/);
  // Precedence order must be stated explicitly: crisis > register > grounding > posture.
  assert.match(prompt, /crisis-safety rule always wins first, then the register rules above, then the grounding rule.*only last this interpretive posture/s);
});

test('groundedReply in stub mode (no GLOO_API_KEY) returns a stub reply grounded on the matched passage, with the stub disclosure', async () => {
  const gloo = createGlooClient({ clientId: undefined, clientSecret: undefined });
  const result = await groundedReply({ topicOrQuestion: 'I feel so weary and tired, is there any rest?', glooClient: gloo });
  assert.equal(result.source, 'stub');
  assert.equal(result.groundedOn.reference, 'Matthew 11:28-30');
  assert.ok(result.groundedOn.text.length > 0);
  assert.equal(
    result.disclosure,
    'This reply is a deterministic offline stub (no AI generation). Only the quoted passage is canonical Scripture text.'
  );
});

test('groundedReply in gloo-api mode (injected fake fetch) returns the Gloo disclosure, distinct from the stub one', async () => {
  const fakeFetch = async (url) => {
    if (url.endsWith('/oauth2/token')) {
      return { ok: true, json: async () => ({ access_token: 'fake-token', expires_in: 3600, token_type: 'Bearer' }) };
    }
    if (url.endsWith('/ai/v2/chat/completions')) {
      return {
        ok: true,
        json: async () => ({
          choices: [
            {
              message: {
                content:
                  'Weariness is a heavy thing to carry, and Scripture speaks to it directly.\n\n' +
                  '"Come to Me, all who are weary and burdened, and I will give you rest. Take My yoke upon you and learn from Me, for I am gentle and humble in heart, and you will find rest for your souls. For My yoke is easy and My burden is light." (Matthew 11:28-30, BSB)\n\n' +
                  'Consider bringing this weariness to God in prayer, and share it with someone who knows you.',
              },
            },
          ],
          model: 'gloo-test',
        }),
      };
    }
    throw new Error(`unexpected URL in test: ${url}`);
  };
  const gloo = createGlooClient({ clientId: 'id', clientSecret: 'secret', fetchImpl: fakeFetch });
  const result = await groundedReply({ topicOrQuestion: 'I feel so weary and tired, is there any rest?', glooClient: gloo });
  assert.equal(result.source, 'gloo-api');
  assert.equal(
    result.disclosure,
    "The commentary in this reply is AI-generated by Gloo AI Studio's models under Gloo's own alignment layer, constrained by this server's grounding and register rules. Only the quoted passage is canonical Scripture text."
  );
  assert.notEqual(result.disclosure, undefined);
});
