#!/usr/bin/env node
// kg-index.cjs — regenerate .knowledge-graph/INDEX.md, the CHEAP navigation
// surface for this repo's local knowledge graph.
//
// Ported from doxa-cns/openclaw. Named .cjs because this repo's package.json
// has "type": "module".
//
// Tokenomics: graph.json can grow large — an agent that reads it whole to
// find one fact pays too much. INDEX.md is one greppable line per entity
// (name + hook), grouped by type; the intended lookup is Grep INDEX.md
// (costs only the matched lines) → read the entity in graph.json directly.
//
// GENERATED — never hand-edit. knowledge-graph-merkle.cjs regenerates it on
// every graph write; run this directly only to rebuild after a manual fix.
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { atomicWrite } = require('./lib/atomic.cjs');

const GRAPH_FILE = path.join(__dirname, '../.knowledge-graph/graph.json');
const INDEX_FILE = path.join(__dirname, '../.knowledge-graph/INDEX.md');
const HOOK_MAX = 110;

// One line per entity: the name (grep anchor) + a hook cut from the first
// observation — enough to judge relevance, never the full content. Sliced by
// code point (Array.from), not UTF-16 code unit (String.slice) — a plain
// .slice() can cut a surrogate pair in half.
function hookFor(entity) {
  const first = (entity.observations && entity.observations[0]) || '';
  const flat = String(first).replace(/\s+/g, ' ').trim();
  const chars = Array.from(flat);
  return chars.length <= HOOK_MAX ? flat : `${chars.slice(0, HOOK_MAX - 1).join('')}…`;
}

function buildIndex(graph) {
  const byType = new Map();
  for (const e of graph.entities || []) {
    const t = e.entityType || 'Untyped';
    if (!byType.has(t)) byType.set(t, []);
    byType.get(t).push(e);
  }
  const types = [...byType.keys()].sort(
    (a, b) => byType.get(b).length - byType.get(a).length || a.localeCompare(b)
  );
  const lines = [
    '# Local KG Index (GENERATED — do not hand-edit)',
    '',
    '<!-- Regenerated by scripts/kg-index.cjs on every graph write. -->',
    '<!-- Lookup: Grep this file for your topic, then read the entity   -->',
    '<!-- directly in .knowledge-graph/graph.json.                     -->',
    '<!-- Never read graph.json whole for a lookup.                    -->',
    '',
  ];
  for (const t of types) {
    lines.push(`## ${t} (${byType.get(t).length})`);
    lines.push('');
    for (const e of byType.get(t).slice().sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`- ${e.name} — ${hookFor(e)}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

// graphFile/indexFile default to the real repo paths so every existing call
// site (CLI, saveGraph()) is unaffected; overridable for tests.
function regenerate(graphFile = GRAPH_FILE, indexFile = INDEX_FILE) {
  const graph = JSON.parse(fs.readFileSync(graphFile, 'utf8'));
  const out = buildIndex(graph);
  atomicWrite(indexFile, out);
  return out.length;
}

module.exports = { buildIndex, hookFor, regenerate, GRAPH_FILE, INDEX_FILE };

if (require.main === module) {
  const bytes = regenerate();
  console.log(`kg-index: wrote ${INDEX_FILE} (${bytes} bytes)`);
}
