/**
 * Loader for the committed BSB (Berean Standard Bible, public domain)
 * fixture set in fixtures/bsb/*.json. These fixtures are the offline
 * fallback for get_passage / verse_of_the_day, and the ground truth corpus
 * verify_quote searches when checking for misattribution.
 *
 * Fixtures are generated by scripts/build-fixtures.js from
 * https://bereanbible.com/bsb.txt (BSB translation, public domain) — never
 * written from model memory. See that script and each fixture's
 * `source`/`fetchedAt` fields for provenance. A secondary WEB fixture set
 * (via bible-api.com) can be built into fixtures/web/*.json with
 * `node scripts/build-fixtures.js --web`, but BSB is the default translation
 * this server, its tests, and the benchmark treat as ground truth.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { tokenize, deSmarten } from './normalize.js';
import { similarity } from './diff.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = path.join(__dirname, '..', 'fixtures', 'bsb');

/** @typedef {{reference: string, translation: string, source: string, fetchedAt: string, text: string, superscription?: string}} Fixture */

/** @type {Fixture[] | null} */
let cache = null;

function normalizeKey(reference) {
  // deSmarten so an en/em-dash verse range ("Psalm 46:1–3") matches the
  // hyphen-range fixture key ("Psalm 46:1-3") — same reasoning as
  // src/usfm.js's humanRefToUsfm.
  return deSmarten(reference).trim().toLowerCase().replace(/\s+/g, ' ');
}

/**
 * Load (and cache) every fixture file.
 * @returns {Fixture[]}
 */
export function loadFixtures() {
  if (cache) return cache;
  let files = [];
  try {
    files = readdirSync(FIXTURES_DIR).filter((f) => f.endsWith('.json'));
  } catch {
    cache = [];
    return cache;
  }
  cache = files
    .map((f) => {
      try {
        return JSON.parse(readFileSync(path.join(FIXTURES_DIR, f), 'utf8'));
      } catch {
        return null;
      }
    })
    .filter(Boolean);
  return cache;
}

/**
 * Look up a fixture by exact (case/whitespace-insensitive) reference match.
 * @param {string} reference
 * @returns {Fixture | undefined}
 */
export function findByReference(reference) {
  const key = normalizeKey(reference);
  return loadFixtures().find((f) => normalizeKey(f.reference) === key);
}

/**
 * Search every fixture for the passage whose text is the best word-level
 * similarity match to the given quote. Used by verify_quote to detect
 * misattribution (a real quote pinned to the wrong reference).
 * @param {string} quote - raw (not yet normalized) quote text
 * @returns {{reference: string, score: number, fixture: Fixture} | null}
 */
export function findBestMatch(quote) {
  const quoteTokens = tokenize(quote);
  if (quoteTokens.length === 0) return null;
  let best = null;
  for (const fixture of loadFixtures()) {
    const score = similarity(tokenize(fixture.text), quoteTokens);
    if (!best || score > best.score) {
      best = { reference: fixture.reference, score, fixture };
    }
  }
  return best;
}

/** @returns {number} */
export function fixtureCount() {
  return loadFixtures().length;
}
