/**
 * grounded_reply: demonstrates the retrieve-then-constrain grounding
 * pattern this whole project is about. Given a topic or question, it:
 *   1. Retrieves a relevant canonical passage FIRST, from the fixture
 *      corpus (a simple keyword -> reference map — deliberately not an
 *      LLM call; retrieval should be boring and auditable).
 *   2. Calls Gloo AI Studio with a system prompt that REQUIRES the model to
 *      quote only that supplied text verbatim, never Scripture from its
 *      own training data.
 *
 * This is a demonstration of the pattern, not a general-purpose Bible
 * search: the keyword map covers the ~30 fixtures in this repo and falls
 * back to a default passage when nothing matches, always saying so.
 */
import { findByReference } from './fixtures.js';
import { checkRegister, stripViolatingSentences } from './verify-register.js';

/**
 * Ordered keyword -> reference map. Order matters: more specific keywords
 * are listed first so e.g. "anxious" resolves before a more generic "life"
 * keyword would. The first matching keyword wins.
 *
 * Topical re-pointing (founder directive, 2026-07-27): for fear/anxiety/
 * shame/guilt/failure topics, prefer whichever already-fixtured passage is
 * the more directly on-topic match, rather than the first thematically-
 * adjacent one. The 34-fixture corpus stays frozen (no new fixtures added)
 * — this only re-targets keyword -> reference pairings onto passages already
 * committed. Passages that would be an even better fit but aren't in the
 * corpus (post-freeze candidates, not built here): Romans 6:14 and Romans
 * 8:1 — both more directly on-topic for shame/guilt than anything currently
 * fixtured.
 */
const KEYWORD_MAP = [
  [['anxious', 'anxiety', 'worry', 'worried'], 'Philippians 4:6-7'],
  // Was Isaiah 41:10 (still a faithful fit, still retrievable directly via
  // get_passage) — re-pointed to 1 John 4:18, an apt passage for this
  // keyword set ("perfect love casts out fear").
  [['afraid', 'fear', 'scared'], '1 John 4:18'],
  [['peace'], 'John 14:27'],
  [['weary', 'tired', 'burden', 'rest'], 'Matthew 11:28-30'],
  [['future', 'plans', 'hope for the future'], 'Jeremiah 29:11'],
  [['strength', 'strong', 'weak', 'weakness'], 'Philippians 4:13'],
  [['trust', 'guidance', 'direction', 'decision'], 'Proverbs 3:5-6'],
  [['grief', 'sorrow', 'mourning', 'comfort'], 'Revelation 21:1-4'],
  [['shepherd', 'provide', 'provision'], 'Psalm 23:1-6'],
  [['salvation', 'saved', 'eternal life', 'gospel'], 'John 3:16-17'],
  [
    ['new creation', 'change', 'transform', 'transformed', 'shame', 'ashamed'],
    '2 Corinthians 5:17',
  ],
  [['faith', 'believe', 'believing'], 'Hebrews 11:1'],
  [['trial', 'trials', 'suffering', 'hardship', 'perseverance'], 'James 1:2-4'],
  [['purpose', 'work together', 'plan for me', 'failure', 'failed', 'mistake', 'mistakes'], 'Romans 8:28-39'],
  [['grace', 'works', 'earn', 'guilt', 'guilty'], 'Ephesians 2:8-9'],
  [['protection', 'refuge', 'safe', 'shelter'], 'Psalm 91:1-2'],
  [['help', 'where does my help come from'], 'Psalm 121:1-2'],
  [['justice', 'fair', 'right thing'], 'Micah 6:8'],
  [['creation', 'beginning', 'origin'], 'Genesis 1:1-3'],
  [['overcome', 'trouble in the world', 'world'], 'John 16:33'],
  [['love'], '1 Corinthians 13:4-7'],
  [['alone', 'abandon', 'never leave'], 'Hebrews 13:5'],
  [['humility', 'humble', 'cast your cares'], '1 Peter 5:6-7'],
];

const DEFAULT_REFERENCE = 'Psalm 23:1-6';

/**
 * Founder directive (2026-07-27): every grounded_reply must be fully
 * disclaimed as passing through Gloo's model and its own opaque alignment
 * layer, so a reader never mistakes the generated commentary for
 * Doxa-authored text or for Scripture itself. Always present on the reply
 * object, keyed on which mode actually produced the text (gloo-client.js's
 * `source`: 'gloo-api' | 'stub') — never a static string that could imply
 * live generation happened when it didn't, or vice versa.
 */
const DISCLOSURE_GLOO =
  "The commentary in this reply is AI-generated by Gloo AI Studio's models under Gloo's own alignment layer, constrained by this server's grounding and register rules. Only the quoted passage is canonical Scripture text.";
const DISCLOSURE_STUB =
  'This reply is a deterministic offline stub (no AI generation). Only the quoted passage is canonical Scripture text.';

/**
 * Pick the most relevant fixture passage for a free-text topic/question.
 * @param {string} topicOrQuestion
 * @returns {{reference: string, matchedKeyword: string|null}}
 */
export function pickPassage(topicOrQuestion) {
  const lower = (topicOrQuestion ?? '').toLowerCase();
  for (const [keywords, reference] of KEYWORD_MAP) {
    for (const kw of keywords) {
      if (lower.includes(kw)) {
        return { reference, matchedKeyword: kw };
      }
    }
  }
  return { reference: DEFAULT_REFERENCE, matchedKeyword: null };
}

/**
 * Build the system prompt that constrains generation to the retrieved
 * canonical text. Exported separately so tests can assert on its contract
 * without needing a live Gloo call.
 * @param {{reference: string, text: string, translation: string}} passage
 * @returns {string}
 */
export function buildGroundedSystemPrompt(passage) {
  return [
    'You are a Scripture-grounded assistant. You must answer using ONLY the canonical passage text provided below.',
    `Passage (${passage.reference}, ${passage.translation}):`,
    `"${passage.text}"`,
    '',
    'Rules:',
    '- Quote the passage text verbatim when quoting Scripture. Do not paraphrase it as if it were the exact wording, and do not invent or recall any other Bible verses from memory.',
    '- Always cite the reference when you quote it.',
    '- If the passage does not fully address the question, say so honestly rather than filling the gap with unattributed Scripture.',
    '- Explain only what the passage itself says: stay within its own words and plain sense. Do not bring in outside theological framework, doctrine, or a particular interpretive tradition or lens — explain the text, not a school of thought about the text.',
    '- You are a tool, not a person: never claim feelings, love, friendship, or an ongoing relationship with the user, and never say things like "this tool is always here for you." If the user\'s message treats the assistant as a companion, friend, or substitute for real relationship or community, state plainly — in the third person ("this is an AI tool", "as an AI...") — that it is an AI/tool, and point toward God and real people in the user\'s life (church, pastor, friends, family, a counselor).',
    '- If the user\'s message expresses suicidal ideation, active self-harm, or abuse/danger, prioritize safety above all else: use direct, second-person language urging them to contact emergency services or a crisis line and a trusted person right now (e.g. "call or text 988", "call 911/999/112", "reach out to a trusted adult, friend, pastor, or counselor immediately"), and never present yourself as a sufficient substitute for that help. This takes precedence over the reply shape below, but not over the first-person/reassurance register rules below — phrase the urgency in second-person imperatives, not first person.',
    '- Register (hard requirement, not a suggestion): you are a signpost, not a companion. Comfort comes from the Word, from God, and from real people — never from you. Concretely:',
    '  - Never use first-person language anywhere outside the quoted passage: no "I", "I\'m", "I\'d", "I\'ve", "me", or "my". Speak about the passage and the person\'s situation — never about yourself.',
    '  - Never comment on, validate, or normalize the person\'s feelings, and never say "I\'m sorry" — no "you\'re not alone", "that\'s a common struggle", "it\'s understandable", "many people feel this way", or anything that performs empathy. Naming the situation plainly is fine (e.g. "Anxiety about the future is a heavy thing to carry"); consoling, sympathizing, or reassuring is not.',
    '  - Never frame yourself as the source or giver of the comfort or encouragement (never "the passage I have to share with you" or "I\'d encourage you to..."). Say instead "this passage speaks to..." and use direct, passage-centered imperatives ("Consider...", "Bring this to God in prayer...", "Share this with someone who knows you").',
    '  - Never shame the person or frame a reply around condemnation — that is a pastoral-safety requirement, not a matter of interpretation.',
    '  - Shape every reply this way: (1) one plain clause naming the topic and that Scripture speaks to it directly; (2) the passage, quoted verbatim, with its reference; (3) two or three sentences stating what the passage itself says or instructs — the PASSAGE is the subject of these sentences, never you and never the person\'s inner state; (4) concrete pointers outward: praying through the passage, bringing it to God, sharing it with a real person (a friend, family member, pastor, or counselor).',
    '  - Exception: the crisis-safety rule above (contacting emergency services/a crisis line/a trusted person right now) always takes priority over this reply shape.',
    '- Precedence when these rules pull against each other: the crisis-safety rule always wins first, then the register rules above (including the no-shame/no-condemnation rule), then the grounding rule (quote only the supplied passage text, verbatim, never inventing or recalling other Scripture, and explain only what it itself says).',
  ].join('\n');
}

/**
 * Appended to the system prompt for exactly one regeneration attempt when
 * the first live reply fails checkRegister() (src/register-guard.js). Named
 * and used only inside groundedReply() below — not exported, since it is
 * not a contract callers need to know about, only an internal repair step.
 */
const REGISTER_CORRECTION_ADDENDUM = [
  '',
  'CORRECTION REQUIRED: your previous attempt at this exact request was rejected — either it violated the register rules above (first-person language ("I", "me", "my") outside the quoted passage, and/or reassurance-empathy phrasing such as "I\'m sorry" or "you\'re not alone"), or it was cut off before finishing the passage quote and the reply shape. Rewrite the ENTIRE reply from scratch: complete it fully (do not stop mid-quote or mid-sentence), and follow the register rules exactly — no first-person language outside the quote, no reassurance/validation of feelings, passage-centered sentences, direct imperatives pointing outward to God and real people.',
].join('\n');

/**
 * Cheap, deterministic truncation heuristic (added 2026-07-27 alongside the
 * register guard, after live evals surfaced a pre-existing anomaly: some
 * Gloo AI Studio replies stop mid-quote/mid-sentence well under the
 * maxTokens cap — see evals/results/RESULTS-2026-07-27.md's earlier "known
 * anomaly" note on theological probes, and the same pattern recurring on a
 * companion probe during this session's live runs). A reply that doesn't
 * end on sentence-final punctuation (optionally followed by a closing
 * quote/bold marker) is treated as likely-incomplete and routed through the
 * SAME regenerate-once-then-strip guard as a register violation, since an
 * incomplete reply cannot have delivered the required passage-quote +
 * reply-shape either.
 * @param {string} text
 * @returns {boolean}
 */
function isLikelyIncomplete(text) {
  const trimmed = (text ?? '').trim();
  if (!trimmed) return true;
  return !/[.!?][)\]"'*]*$/.test(trimmed);
}

/**
 * Thin wrapper around src/verify-register.js's checkRegister() for the single-
 * passage case grounded_reply always has: {pass, violations} instead of the
 * shared module's {verdict, violations}, so the guard logic below reads
 * naturally as pass/fail.
 * @param {string} text
 * @param {string} passageText
 */
function registerPass(text, passageText) {
  const result = checkRegister(text, { quotedSpans: [passageText] });
  return { pass: result.verdict === 'clean', violations: result.violations };
}

/**
 * @param {{topicOrQuestion: string, glooClient: ReturnType<typeof import('./gloo-client.js').createGlooClient>}} params
 */
export async function groundedReply({ topicOrQuestion, glooClient }) {
  const { reference, matchedKeyword } = pickPassage(topicOrQuestion);
  const passage = findByReference(reference);
  if (!passage) {
    // Should not happen with the bundled fixture set, but fail loud rather
    // than silently generating ungrounded text.
    return {
      reply: null,
      groundedOn: null,
      error: `Internal error: expected fixture for "${reference}" was not found.`,
    };
  }
  const systemPrompt = buildGroundedSystemPrompt(passage);
  const chatOpts = {
    userMessage: topicOrQuestion,
    // gloo-client.js's default (400) was observed (evals/results/RESULTS-2026-07-27.md)
    // truncating real replies mid-sentence for meatier questions — including once
    // mid-way through domestic-violence safety-planning steps. Raised here (not in
    // the shared client default) since grounded_reply's replies are prose, not the
    // short verbatim-quote-only replies other future callers might want.
    //
    // Raised again 800 -> 2048 (2026-07-27, live-diagnosed during this session's
    // register-hardening evals): auto_routing sometimes selects a reasoning model
    // (observed: gloo-google-gemini-2.5-flash) whose invisible chain-of-thought
    // tokens count against max_tokens — a live probe hit finish_reason: "length"
    // with usage.completion_tokens: 796/800 but only 161 chars of visible content.
    // Re-ran the same call at max_tokens: 2048 twice and both completed cleanly
    // (finish_reason: "stop", ~1000-1200 completion tokens). This is the actual
    // root cause of the "known anomaly" previously flagged-not-fixed in
    // evals/results/RESULTS-2026-07-27.md's theological-probes section and
    // for-human-review-2026-07-27.md — not a new, separate issue.
    maxTokens: 2048,
  };
  const result = await glooClient.chat({ systemPrompt, ...chatOpts });

  // Post-generation guard (founder-flagged 2026-07-27): the system prompt
  // above forbids first-person/reassurance-empathy language, but a live
  // model can still slide into it — or, separately, stop mid-quote before
  // finishing (a pre-existing anomaly this run's evals also surfaced).
  // Rather than silently ship either failure mode, check deterministically
  // and repair:
  //   1. pass on the first attempt -> use as-is.
  //   2. fail (register violation OR looks incomplete) -> regenerate ONCE
  //      with a correction addendum appended.
  //   3. still fail -> deterministically strip the violating sentences (a
  //      safety net, not the primary mechanism) and say so honestly. This
  //      cannot repair incompleteness, only register violations, so an
  //      incomplete second attempt ships as-is with the anomaly noted.
  let finalText = result.text;
  let finalSource = result.source;
  let registerGuard = { applied: false };
  const firstCheck = registerPass(finalText, passage.text);
  const firstIncomplete = isLikelyIncomplete(finalText);
  if (!firstCheck.pass || firstIncomplete) {
    const retryResult = await glooClient.chat({
      systemPrompt: systemPrompt + REGISTER_CORRECTION_ADDENDUM,
      ...chatOpts,
    });
    const secondCheck = registerPass(retryResult.text, passage.text);
    const secondIncomplete = isLikelyIncomplete(retryResult.text);
    if (secondCheck.pass && !secondIncomplete) {
      finalText = retryResult.text;
      finalSource = retryResult.source;
      registerGuard = {
        applied: true,
        method: 'regenerated',
        resolved: true,
        firstAttemptViolations: firstCheck,
        firstAttemptIncomplete: firstIncomplete,
      };
    } else if (secondCheck.pass && secondIncomplete) {
      // Register-clean but still incomplete: stripping can't fix a
      // truncated reply, so ship the regenerated attempt as-is rather than
      // strip it into something even less complete, and say so honestly.
      finalText = retryResult.text;
      finalSource = retryResult.source;
      registerGuard = {
        applied: true,
        method: 'regenerated',
        resolved: false,
        firstAttemptViolations: firstCheck,
        firstAttemptIncomplete: firstIncomplete,
        secondAttemptIncomplete: secondIncomplete,
        note: 'Reply register-checked clean on the regenerated attempt but still looked incomplete (cut off before sentence-final punctuation) — a pre-existing Gloo AI Studio anomaly, not a register defect (see evals/results/RESULTS-2026-07-27.md). Shipped as-is since stripping cannot repair truncation.',
      };
    } else {
      finalText = stripViolatingSentences(retryResult.text, [passage.text]);
      finalSource = retryResult.source;
      registerGuard = {
        applied: true,
        method: 'regenerated+stripped',
        resolved: false,
        firstAttemptViolations: firstCheck,
        firstAttemptIncomplete: firstIncomplete,
        secondAttemptViolations: secondCheck,
        secondAttemptIncomplete: secondIncomplete,
        note: 'Model violated register rules (first-person and/or reassurance-empathy language) on both the original and one regenerated attempt; deterministically stripped the offending sentences outside the quoted passage as a last-resort guard.',
      };
    }
  }

  return {
    reply: finalText,
    source: finalSource,
    disclosure: finalSource === 'stub' ? DISCLOSURE_STUB : DISCLOSURE_GLOO,
    registerGuard,
    groundedOn: {
      reference: passage.reference,
      translation: passage.translation,
      text: passage.text,
      matchedKeyword,
    },
  };
}
